# Generated by ChatGPT on 2025-12-19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_product_alter_sale_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='sales',
                to='products.product',
            ),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
